// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: event_query.sql

package database

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
insert into storage.events
    (aggregate_type, aggregate_id, type, payload)
values ($1,
        $2,
        $3,
        $4) returning id
`

type CreateEventParams struct {
	AggregateType string
	AggregateID   string
	Type          string
	Payload       []byte
}

func (q *Queries) CreateEvent(ctx context.Context, arg *CreateEventParams) (string, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.Type,
		arg.Payload,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
