// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: event_query.sql

package database

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :exec
insert into storage.events
    (id, name, payload, status, producer, timestamp)
values ($1,
        $2,
        $3,
        $4,
        $5,
        $6)
`

type CreateEventParams struct {
	ID        string
	Name      string
	Payload   []byte
	Status    string
	Producer  string
	Timestamp time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg *CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.Name,
		arg.Payload,
		arg.Status,
		arg.Producer,
		arg.Timestamp,
	)
	return err
}
