// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type StorageBucket struct {
	ID                   string
	Version              int32
	Name                 string
	AllowedMimeTypes     []string
	MaxAllowedObjectSize *int64
	Public               bool
	Disabled             bool
	Locked               bool
	LockReason           *string
	LockedAt             *time.Time
	CreatedAt            time.Time
	UpdatedAt            *time.Time
}

type StorageEvent struct {
	ID            string
	Version       int32
	AggregateType string
	AggregateID   string
	Type          string
	Payload       []byte
	CreatedAt     time.Time
}

type StorageObject struct {
	ID             string
	Version        int32
	BucketID       string
	Name           string
	PathTokens     []string
	MimeType       string
	Size           int64
	Metadata       []byte
	UploadStatus   string
	LastAccessedAt *time.Time
	LockedAt       *time.Time
	CreatedAt      time.Time
	UpdatedAt      *time.Time
}
